### PR TITLE
#9 Recent version of D-Flow FM does not run in OpenDA

### PR DESCRIPTION
**Pull request by erikpelgrim**
Add functionality for 3 columns when astronomic or harmonic
Make checks case insensitive
Add test case for provided example file

### CODE REVIEW

**Comment by nilsvanvelzen** [comment]
Hi Erik, the continuous integration tests are failing on your branch. This needs to be fixed before it can be merged/pullen into the master.

If you need some help debugging Travis runs just let me know
=>
BUILD FAILED
/home/travis/build/OpenDA-Association/public/build.xml:604: Test org.openda.model_dflowfm.BcFileTest failed
<=

**Comment by erikpelgrim** [comment]
@nilsvanvelzen Test succeeds locally and I detect no significant differences between my branch, my code and the master. So yes help debugging travis would be appreciated

**Comment by erikpelgrim** [comment]
@nilsvanvelzen Do you know what is needed to see in/on GitHub why tests are failing? Would it be possible to have (and pay) for that?

**Comment by nilsvanvelzen** [comment]
Some initial tips:

To see the output from travis:
*You navigate to your branch in GitHub and click on "commits"
*At your last commit your click on the red x that links to the failed test select the correct one (not the one that corresponds to your push request).
* You see the three platforms were are testing on (3 JDK versions). Since all are red just select one (eg. build 51.1)
*now you can see the job log with nice colours. Sometimes it is better to look at the raw output.

Now you only see that Test org.openda.model_dflowfm.BcFileTest failed

*Fix your test: first the obvious, did you make changes that might touch this test? Did you forget to add new files to the test? Does this test contain comparison of floats without tolerance (or worst compare the "tostring" version of the output (=poor test)

*Get some more output out of the test:

TIP try to resolve the problems on a new branch. Hence make a branch, you can make all the changes for debugging you want. At the end you only cherry-pick the changes you want to keep on your current branch.


look in the build.xml (root OpenDA) for
<target name="test-travis" depends="build,testclasses">

and change 

\<junit printsummary="yes" haltonfailure="yes" fork="yes" timeout="1200000" maxmemory="${maxmemory}">

into 

\<junit printsummary="withOutAndErr" dir="${projectdir}" fork="yes" timeout="1200000" maxmemory="${maxmemory}">

commit this new build.xml and push it on your branch. That will make the test running with more output. In this mode you can play a bit with adding some prints/output to the failing tests. Sorry: no debugger available.

NOTE: there is a limit to the amount of output travis can deal with. sometimes you have to temporarily switch on other tests to limit the amount of output.

Good luck

**Comment by erikpelgrim** [comment]
Fixed by using correct file name (upper case L), wil create a new branch with clean code and make a new pull request.

**Pull request closed without merging**
